spring:
  datasource:
    url: jdbc:postgresql://192.168.50.3:5432/test_db
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    path: /api-docs/v3/api-docs
  swagger-ui:
    path: /api-docs/swagger-ui
    disable-swagger-default-url: true